return {
  require 'plugins.colorizer',
  require 'plugins.vim-sleuth',
  require 'plugins.gitsigns',
  require 'plugins.whichkey.lua',
  require 'plugins.telescope',
  require 'plugins.lazydev',
  require 'plugins.luvit-meta',
  require 'plugins.lsp',
  require 'plugins.conform',
  require 'plugins.nvim-cmp',
  require 'plugins.tokyonight',
  require 'plugins.todo-comments',
  require 'plugins.mini',
  require 'plugins.treesitter',
  require 'plugins.debug',
  require 'plugins.indent_line',
  require 'plugins.lint',
  require 'plugins.autopairs',
  require 'plugins.neo-tree',
  require 'plugins.gitsigns', -- adds gitsigns recommend keymaps
  require 'plugins.copilot',
  require 'plugins.floatterm',
  { import = 'custom.plugins' },
}
